version: '3.7'

services:
    postgres:
        image: "postgres:14.0"
        container_name: ${COMPOSE_PROJECT_NAME}_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/
            TZ: ${TZ}
        volumes:
            - ./postgres_data/:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
